name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "$HOME/service-account.json"
          firebase auth:login:ci --token "$(cat $HOME/service-account.json)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting